/**
 * The scanner and the check, held to synthetic files that each carry one defect a G-code check has to catch.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import assert from "node:assert/strict";
import { after, test } from "node:test";

import { check, firstValue, scan } from "../src/gcode.js";

// Every scratch folder a test makes goes when the file is done.
const made: string[] = [];
function scratch(): string {
  const dir = mkdtempSync(join(tmpdir(), "b2f-test-"));
  made.push(dir);
  return dir;
}
after(() => {
  for (const dir of made) rmSync(dir, { recursive: true, force: true });
});

const HEAD = `; generated by Flash Studio 1.7.9 on 2026-01-01 at 00:00:00
; CONFIG_BLOCK_START
; printer_model = Flashforge Adventurer 5M
; nozzle_diameter = 0.4
; gcode_flavor = klipper
; printable_area = -110x-110,110x-110,110x110,-110x110
; filament_type = PLA
; nozzle_temperature = 220
; curr_bed_type = Textured PEI Plate
; textured_plate_temp = 55
; filament used [mm] = 100
; total layer number = 1
; CONFIG_BLOCK_END
M190 S55
M104 S220
G90
M83
G1 Z0.2 F600
`;

function gcode(body: string): string {
  const path = join(scratch(), "t.gcode");
  writeFileSync(path, HEAD + body);
  return path;
}

const near = (got: number | null, want: number, tol = 0.02) =>
  assert.ok(got !== null && Math.abs(got - want) < tol, `expected ${want}, got ${got}`);

test("an arc bulging off the bed is caught, though both its ends sit inside", () => {
  const path = gcode("G1 X108 Y-5 E1\nG3 X108 Y5 I0 J5 E1\n");
  const s = scan(path);
  assert.equal(s.arcs, 1);
  near(s.x[1], 113, 0.001);
  assert.equal(check(path).code, 2);
});

test("an arc inside the bed still passes", () => {
  const path = gcode("G1 X50 Y50 E1\nG3 X50 Y60 I0 J5 E1\n");
  near(scan(path).x[1], 55, 0.001);
  assert.equal(check(path).code, 0);
});

test("a relative move is resolved, not read as an absolute one", () => {
  const path = gcode("G1 X100 Y0 E1\nG91\nG1 X20 E1\nG90\n");
  const s = scan(path);
  near(s.x[1], 120, 0.001);
  assert.equal(s.relativeMoves, 1);
  assert.equal(check(path).code, 2);
});

test("G92 moves the origin under every later move", () => {
  const s = scan(gcode("G1 X100 Y0 E1\nG92 X0\nG1 X60 E1\n"));
  near(s.x[1], 100, 0.001);
});

test("max Z follows a relative lift", () => {
  near(scan(gcode("G91\nG1 Z10 F600\nG90\n")).maxZ, 10.2, 0.001);
});

test("a header value written once per slot reads as the slot that prints", () => {
  assert.equal(firstValue("PETG;PETG;PETG"), "PETG");
  assert.equal(firstValue("255,255,255"), "255");
  assert.equal(firstValue(undefined), "");
});

test("a tool change the 5M cannot make fails the check", () => {
  const path = gcode("T0\nG1 X10 Y10 E1\nT1\nG1 X20 Y10 E1\n");
  assert.deepEqual(scan(path).tools.map((t) => t.tool), [0, 1]);
  const r = check(path);
  assert.equal(r.code, 2);
  assert.ok(r.failures.some((f) => f.includes("one extruder") && f.includes("T1")), r.failures.join("\n"));
});

test("T0 alone is the one extruder, and a Klipper macro starting with T is not a tool", () => {
  const r = check(gcode("T0\nTIMELAPSE_TAKE_FRAME\nG1 X10 Y10 E1\n"));
  assert.equal(r.code, 0, r.failures.join("\n"));
});

// A Bambu project printed from slot 2 with 0 mm on slot 1 must not read as an empty slice.
function multiSlot(body: string): string {
  const head = HEAD
    .replace("; filament_type = PLA", "; filament_type = PETG;PLA;PETG")
    .replace("; nozzle_temperature = 220", "; nozzle_temperature = 255,220,255")
    .replace("; textured_plate_temp = 55", "; textured_plate_temp = 70,55,70")
    .replace("; filament used [mm] = 100", "; filament used [mm] = 0.00, 120.50, 0.00");
  const path = join(scratch(), "t.gcode");
  writeFileSync(path, head + body);
  return path;
}

test("filament is counted on every slot, and temperatures are read for the slot that prints", () => {
  const r = check(multiSlot("T1\nG1 X10 Y10 E1\n"));
  assert.equal(r.facts.filamentMm, "120.50");
  assert.equal(r.facts.filamentType, "PLA");
  assert.equal(r.facts.nozzleC, "220");
  assert.equal(r.facts.bedC, "55");
  // The only failure is the tool change: not an empty slice, not a PETG temperature on a PLA plate.
  assert.equal(r.failures.length, 1, r.failures.join("\n"));
  assert.match(r.failures[0] ?? "", /one extruder/);
});

test("a plate drawing from two slots fails even if it names them another way", () => {
  const path = multiSlot("G1 X10 Y10 E1\n");
  writeFileSync(path, readFileSync(path, "utf8").replace("0.00, 120.50, 0.00", "10.00, 120.50, 0.00"));
  const r = check(path);
  assert.equal(r.facts.filamentMm, "130.50");
  assert.ok(r.failures.some((f) => f.includes("slots 1, 2")), r.failures.join("\n"));
});
