/**
 * Reading a G-code file the way the printer will read it, and holding it to the machine before it moves.
 *
 * The scan follows the modal state a firmware follows — G90/G91, G92, and G2/G3 arcs by the extremes they sweep
 * through rather than by their endpoints. An endpoint-only reading misses an arc that bulges past the bed edge,
 * and reads a relative move as an absolute one; both were real gaps, both are covered by tests.
 */
import { readFileSync } from "node:fs";
import { basename } from "node:path";

import {
  BAMBU_MARKERS, BED_MAX, BED_MIN, BED_TEMP_KEY, BED_TOLERANCE, BED_TYPE, BED_Z, HW, NOZZLE, PRINTER_MODEL,
  TEMP_RANGE,
} from "./machine.js";

const PARAM = /([A-Za-z])\s*([-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)/g;

/**
 * Commands that change what the printer believes about itself rather than moving it: the Z offset, the position it
 * thinks it is at, its saved configuration. The AD5M's own start block uses SET_PRESSURE_ADVANCE and
 * SET_VELOCITY_LIMIT, which only set print parameters, so those are not here. Checked against a sliced file: a clean
 * AD5M G-code carries none of these, and its one G92 is G92 E0.
 */
const STATE_COMMANDS = /^\s*(SET_GCODE_OFFSET|SET_KINEMATIC_POSITION|SET_HOME_OFFSET|SAVE_CONFIG|FIRMWARE_RESTART|RESTART|M500|M502)\b/i;

/** The '; key = value' block a slicer writes, plus its totals lines. Stops at the end of the config block. */
export function header(path: string): Map<string, string> {
  const h = new Map<string, string>();
  for (const line of readFileSync(path, "utf8").split("\n")) {
    if (!line.startsWith("; ")) continue;
    const body = line.slice(2).replace(/\r$/, "");
    if (body.startsWith("generated by ")) {
      h.set("generated by", body.slice("generated by ".length));
      continue;
    }
    if (body.includes("CONFIG_BLOCK_END")) break;
    const eq = body.indexOf(" = ");
    if (eq > 0) {
      h.set(body.slice(0, eq).trim(), body.slice(eq + 3).trim().replace(/^"|"$/g, ""));
      continue;
    }
    const colon = body.indexOf(": ");
    if (colon > 0 && !h.has(body.slice(0, colon).trim())) {
      h.set(body.slice(0, colon).trim(), body.slice(colon + 2).trim());
    }
  }
  return h;
}

/** A value a header writes once per filament slot, read for one slot. */
export function slotValue(value: string | undefined, slot: number): string {
  const values = (value ?? "").split(/[;,]/);
  return (values[slot] ?? values[0] ?? "").trim();
}

export function firstValue(value: string | undefined): string {
  return slotValue(value, 0);
}

export interface Scan {
  bambuHits: Array<{ line: number; text: string }>;
  maxZ: number | null;
  x: [number, number] | [null, null];
  y: [number, number] | [null, null];
  hasNozzleHeat: boolean;
  hasBedHeat: boolean;
  arcs: number;
  relativeMoves: number;
  /** The highest the file asks for, whatever its header claims. */
  maxFeedXY: number;
  maxFeedZOnly: number;
  maxAccel: number;
  maxNozzleC: number;
  maxBedC: number;
  layers: number;
  /** Every T command, in order. The 5M has one extruder: anything but T0 is a change it cannot make. */
  tools: Array<{ line: number; tool: number }>;
  /** The line "; EXECUTABLE_BLOCK_START" sits on, when the file has one. */
  executableStart: number | null;
  /** Commands before that marker. In a file the slicer wrote there are none: the first is the line after it. */
  beforeStart: Array<{ line: number; text: string }>;
  /** Commands that move the printer's own idea of where it is, or rewrite its configuration. */
  stateCommands: Array<{ line: number; text: string }>;
}

/** Every point an arc can reach: its end, plus each axis extreme the sweep passes through. */
export function arcPoints(
  x0: number, y0: number, x1: number, y1: number, i: number, j: number, clockwise: boolean,
): Array<[number, number]> {
  const cx = x0 + i;
  const cy = y0 + j;
  const r = Math.hypot(x0 - cx, y0 - cy);
  let a0 = Math.atan2(y0 - cy, x0 - cx);
  let a1 = Math.atan2(y1 - cy, x1 - cx);
  const full = Math.hypot(x1 - x0, y1 - y0) < 1e-9;
  if (clockwise) {
    if (full || a1 > a0) a1 -= 2 * Math.PI;
  } else {
    if (full || a1 < a0) a1 += 2 * Math.PI;
  }
  const lo = clockwise ? a1 : a0;
  const hi = clockwise ? a0 : a1;
  const points: Array<[number, number]> = [];
  points.push([x1, y1]);
  const quarter = Math.PI / 2;
  for (let k = Math.ceil(lo / quarter); k <= Math.floor(hi / quarter); k++) {
    points.push([cx + r * Math.cos(k * quarter), cy + r * Math.sin(k * quarter)]);
  }
  return points;
}

function params(rest: string): Map<string, number> {
  const out = new Map<string, number>();
  PARAM.lastIndex = 0;
  for (let m = PARAM.exec(rest); m; m = PARAM.exec(rest)) {
    out.set((m[1] ?? "").toUpperCase(), Number.parseFloat(m[2] ?? "0"));
  }
  return out;
}

/** One pass over the whole file. Everything the check needs, measured rather than believed. */
export function scan(path: string): Scan {
  const s: Scan = {
    bambuHits: [], maxZ: null, x: [null, null], y: [null, null],
    hasNozzleHeat: false, hasBedHeat: false, arcs: 0, relativeMoves: 0,
    maxFeedXY: 0, maxFeedZOnly: 0, maxAccel: 0, maxNozzleC: 0, maxBedC: 0, layers: 0, tools: [],
  
    executableStart: null, beforeStart: [], stateCommands: [],
  };
  let minX: number | null = null, maxX: number | null = null, minY: number | null = null, maxY: number | null = null;
  const see = (x: number, y: number) => {
    minX = minX === null || x < minX ? x : minX;
    maxX = maxX === null || x > maxX ? x : maxX;
    minY = minY === null || y < minY ? y : minY;
    maxY = maxY === null || y > maxY ? y : maxY;
  };

  let px = 0, py = 0, pz = 0, feed = 0;
  let absolute = true;
  let lineNo = 0;

  for (const raw of readFileSync(path, "utf8").split("\n")) {
    lineNo++;
    if (raw.startsWith(";")) {
      if (raw.startsWith(";LAYER_CHANGE")) s.layers++;
      if (s.executableStart === null && raw.includes("EXECUTABLE_BLOCK_START")) s.executableStart = lineNo;
      continue;
    }
    if (s.executableStart === null && raw.trim()) s.beforeStart.push({ line: lineNo, text: raw.trim().slice(0, 60) });
    if (STATE_COMMANDS.test(raw)) s.stateCommands.push({ line: lineNo, text: raw.trim().slice(0, 60) });
    if (raw.startsWith("M104") || raw.startsWith("M109")) s.hasNozzleHeat = true;
    if (raw.startsWith("M140") || raw.startsWith("M190")) s.hasBedHeat = true;
    for (const marker of BAMBU_MARKERS) {
      if (marker.test(raw)) {
        s.bambuHits.push({ line: lineNo, text: raw.trim().slice(0, 60) });
        break;
      }
    }
    const code = (raw.split(";", 1)[0] ?? "").trim();
    if (!code) continue;
    const word = (code.split(/\s+/, 1)[0] ?? "").toUpperCase();

    const tool = /^T(\d+)$/.exec(word);
    if (tool) { s.tools.push({ line: lineNo, tool: Number(tool[1]) }); continue; }
    if (word === "G90") { absolute = true; continue; }
    if (word === "G91") { absolute = false; continue; }

    if (word === "M104" || word === "M109" || word === "M140" || word === "M190") {
      const value = params(code.slice(word.length)).get("S");
      if (value !== undefined) {
        if (word === "M104" || word === "M109") s.maxNozzleC = Math.max(s.maxNozzleC, value);
        else s.maxBedC = Math.max(s.maxBedC, value);
      }
      continue;
    }
    if (word === "M204") {
      const value = params(code.slice(word.length)).get("S");
      if (value !== undefined) s.maxAccel = Math.max(s.maxAccel, value);
      continue;
    }
    if (word === "SET_VELOCITY_LIMIT") {
      const accel = /ACCEL=([\d.]+)/i.exec(code);
      if (accel) s.maxAccel = Math.max(s.maxAccel, Number.parseFloat(accel[1] ?? "0"));
      continue;
    }
    if (word !== "G0" && word !== "G1" && word !== "G2" && word !== "G3" && word !== "G92") continue;

    const p = params(code.slice(word.length));
    if (word === "G92") {
      // G92 E0 resets the extruder and is ordinary. G92 on X, Y or Z moves the machine's own idea of where it is.
      if (p.has("X") || p.has("Y") || p.has("Z")) s.stateCommands.push({ line: lineNo, text: code.slice(0, 60) });
      if (p.has("X")) px = p.get("X") ?? px;
      if (p.has("Y")) py = p.get("Y") ?? py;
      if (p.has("Z")) pz = p.get("Z") ?? pz;
      continue;
    }
    const f = p.get("F");
    if (f !== undefined) feed = f;
    const tx = p.has("X") ? (absolute ? (p.get("X") ?? px) : px + (p.get("X") ?? 0)) : px;
    const ty = p.has("Y") ? (absolute ? (p.get("Y") ?? py) : py + (p.get("Y") ?? 0)) : py;
    const tz = p.has("Z") ? (absolute ? (p.get("Z") ?? pz) : pz + (p.get("Z") ?? 0)) : pz;
    if (!absolute && (p.has("X") || p.has("Y") || p.has("Z"))) s.relativeMoves++;

    const hasXY = p.has("X") || p.has("Y");
    if (word === "G2" || word === "G3") {
      s.arcs++;
      if (p.has("I") || p.has("J")) {
        for (const [ax, ay] of arcPoints(px, py, tx, ty, p.get("I") ?? 0, p.get("J") ?? 0, word === "G2")) see(ax, ay);
      } else {
        see(tx, ty);
      }
      s.maxFeedXY = Math.max(s.maxFeedXY, feed / 60);
    } else if (hasXY) {
      see(tx, ty);
      s.maxFeedXY = Math.max(s.maxFeedXY, feed / 60);
    } else if (p.has("Z")) {
      s.maxFeedZOnly = Math.max(s.maxFeedZOnly, feed / 60);
    }
    if (p.has("Z")) s.maxZ = s.maxZ === null || tz > s.maxZ ? tz : s.maxZ;
    px = tx; py = ty; pz = tz;
  }

  s.x = minX === null || maxX === null ? [null, null] : [minX, maxX];
  s.y = minY === null || maxY === null ? [null, null] : [minY, maxY];
  return s;
}

export type CheckState = "ok" | "bad" | "warn";
export interface CheckLine { state: CheckState; text: string; }

export interface CheckResult {
  file: string;
  generatedBy: string;
  lines: CheckLine[];
  failures: string[];
  warnings: string[];
  /** The numbers worth showing beside the verdict. */
  facts: {
    layers: string; maxZ: number | null; timeEstimate: string; filamentMm: string;
    filamentType: string; nozzleC: string; bedC: string; bedType: string;
    arcs: number; relativeMoves: number; maxFeedXY: number; maxAccel: number;
    x: [number, number] | [null, null]; y: [number, number] | [null, null];
  };
  /** Exit 0 clean, 2 do not print it. */
  code: 0 | 2;
}

/**
 * Hold a file to the printer. Every temperature compared here comes out of the header the slicer wrote, and every
 * limit out of the machine's own preset — nothing is typed in.
 */
export function check(path: string): CheckResult {
  const h = header(path);
  const s = scan(path);
  const lines: CheckLine[] = [];
  const failures: string[] = [];
  const warnings: string[] = [];

  const verdict = (ok: boolean, good: string, bad: string) => {
    lines.push({ state: ok ? "ok" : "bad", text: ok ? good : bad });
    if (!ok) failures.push(bad);
  };
  const note = (text: string) => { lines.push({ state: "warn", text }); warnings.push(text); };

  const model = h.get("printer_model") ?? "?";
  verdict(model === PRINTER_MODEL, `printer_model = ${PRINTER_MODEL}`, `printer_model = ${model} (need ${PRINTER_MODEL})`);

  const nozzle = h.get("nozzle_diameter") ?? "?";
  verdict(nozzle.includes(NOZZLE), `nozzle ${nozzle}`, `nozzle_diameter = ${nozzle} (printer has ${NOZZLE})`);

  const flavor = h.get("gcode_flavor") ?? "?";
  verdict(flavor === "klipper", "gcode_flavor = klipper", `gcode_flavor = ${flavor} (AD5M is klipper)`);

  const area = h.get("printable_area") ?? "?";
  verdict(area.startsWith("-110x-110"), `printable_area ${area}`,
    `printable_area = ${area} (need -110x-110,110x-110,110x110,-110x110)`);

  const first = s.bambuHits[0];
  verdict(s.bambuHits.length === 0, "no Bambu-only commands",
    `${s.bambuHits.length} Bambu-only command(s), first at line ${first?.line ?? 0}: ${first?.text ?? ""}`);

  // Which slots the plate draws from: the header lists one length per slot, and a Bambu project may print from slot 10.
  const perSlot = (h.get("filament used [mm]") ?? "0").split(/[;,]/).map((v) => Number.parseFloat(v.trim()));
  const usedSlots = perSlot.flatMap((v, i) => (v > 0 ? [i] : []));
  const slot = usedSlots[0] ?? 0;
  const changes = s.tools.filter((t) => t.tool !== 0);
  const changeText = changes.length
    ? `selects ${[...new Set(changes.map((t) => `T${t.tool}`))].join(", ")} (first at line ${changes[0]?.line ?? 0})`
    : "";
  const slotText = usedSlots.length > 1 ? `draws filament from slots ${usedSlots.map((i) => i + 1).join(", ")}` : "";
  verdict(!changes.length && usedSlots.length <= 1,
    `one extruder: ${s.tools.length ? "T0 only" : "no tool command"}`,
    `the 5M has one extruder and this file ${[changeText, slotText].filter(Boolean).join(" and ")} — re-convert it onto one slot`);

  // A project can put its own text where the slicer writes the file's metadata, and that text lands above the start
  // block, before the first heat and the first home. In a file the slicer wrote, nothing executes there.
  if (s.executableStart !== null) {
    const first = s.beforeStart[0];
    verdict(!s.beforeStart.length,
      `nothing executes before the start block (line ${s.executableStart})`,
      `${s.beforeStart.length} command(s) run before the start block at line ${s.executableStart} — first at line ${first?.line ?? 0}: ${first?.text ?? ""}`);
  }

  // Homing undoes a shifted origin; these are the commands it does not undo.
  const state = s.stateCommands[0];
  verdict(!s.stateCommands.length,
    "no command rewrites the printer's origin or its saved configuration",
    `${s.stateCommands.length} command(s) change the printer's own state — first at line ${state?.line ?? 0}: ${state?.text ?? ""}`);

  verdict(s.maxZ !== null && s.maxZ <= BED_Z, `max Z ${s.maxZ} mm`, `max Z ${s.maxZ} exceeds ${BED_Z} mm`);

  if (s.x[0] !== null && s.y[0] !== null) {
    const [x0, x1] = s.x as [number, number];
    const [y0, y1] = s.y as [number, number];
    const lo = BED_MIN - BED_TOLERANCE;
    const hi = BED_MAX + BED_TOLERANCE;
    const inside = x0 >= lo && x1 <= hi && y0 >= lo && y1 <= hi;
    const seen = s.arcs || s.relativeMoves
      ? ` (${s.arcs} arc(s) swept, ${s.relativeMoves} relative move(s) resolved)`
      : "";
    const range = `X ${x0.toFixed(1)}..${x1.toFixed(1)}  Y ${y0.toFixed(1)}..${y1.toFixed(1)}${seen}`;
    verdict(inside, `XY moves within the bed: ${range}`, `XY moves leave the bed: ${range}`);
  }

  verdict(s.hasNozzleHeat && s.hasBedHeat, "nozzle and bed heaters are set (M104/M109, M140/M190)",
    "a heater is never set — start gcode missing?");

  const bedType = h.get("curr_bed_type") ?? "?";
  const bedKey = BED_TEMP_KEY[bedType] ?? "hot_plate_temp";
  if (bedType in BED_TEMP_KEY) lines.push({ state: "ok", text: `bed type ${bedType} → ${bedKey}` });
  else note(`bed type '${bedType}' unknown; reading ${bedKey}`);

  // Temperatures for the slot that prints, not for slot 1 when the plate never touches it.
  const filamentType = slotValue(h.get("filament_type"), slot) || "?";
  const nozzleC = slotValue(h.get("nozzle_temperature") ?? h.get("nozzle_temperature_initial_layer"), slot);
  const bedC = slotValue(h.get(bedKey) ?? h.get(`${bedKey}_initial_layer`), slot);
  const range = TEMP_RANGE[filamentType.toUpperCase()];
  const nozzleValue = Number.parseFloat(nozzleC);
  const bedValue = Number.parseFloat(bedC);
  if (!Number.isFinite(nozzleValue) || !Number.isFinite(bedValue)) {
    verdict(false, "", `temperatures unreadable: nozzle '${nozzleC}', bed '${bedC}'`);
  } else if (range) {
    const [nLo, nHi] = range.nozzle;
    const [bLo, bHi] = range.bed;
    const limits = `nozzle ${nLo}–${nHi} °C, bed ${bLo}–${bHi} °C`;
    verdict(nozzleValue >= nLo && nozzleValue <= nHi && bedValue >= bLo && bedValue <= bHi,
      `${filamentType}: nozzle ${nozzleC} °C, bed ${bedC} °C, inside ${limits}`,
      `${filamentType}: nozzle ${nozzleC} °C, bed ${bedC} °C, outside ${limits} — wrong filament preset`);
  } else {
    note(`filament_type ${filamentType} has no range on file; nozzle ${nozzleC} °C, bed ${bedC} °C — read them`);
  }

  verdict(s.maxNozzleC <= HW.nozzleMaxC, `highest nozzle command ${s.maxNozzleC.toFixed(0)} °C ≤ hardware ${HW.nozzleMaxC}`,
    `nozzle commanded to ${s.maxNozzleC.toFixed(0)} °C, over the hardware ${HW.nozzleMaxC}`);
  verdict(s.maxBedC <= HW.bedMaxC, `highest bed command ${s.maxBedC.toFixed(0)} °C ≤ hardware ${HW.bedMaxC}`,
    `bed commanded to ${s.maxBedC.toFixed(0)} °C, over the hardware ${HW.bedMaxC}`);
  verdict(s.maxFeedXY <= HW.maxSpeedMmS, `highest XY feedrate ${s.maxFeedXY.toFixed(0)} mm/s ≤ hardware ${HW.maxSpeedMmS}`,
    `feedrate ${s.maxFeedXY.toFixed(0)} mm/s over the hardware ${HW.maxSpeedMmS}`);
  lines.push({
    state: "ok",
    text: `Z-only moves carry up to ${s.maxFeedZOnly.toFixed(0)} mm/s; Klipper clamps Z to its max_z_velocity (${HW.maxZSpeedMmS} on the 5M) itself`,
  });
  verdict(s.maxAccel <= HW.maxAccel, `highest acceleration ${s.maxAccel.toFixed(0)} mm/s² ≤ hardware ${HW.maxAccel}`,
    `acceleration ${s.maxAccel.toFixed(0)} over the hardware ${HW.maxAccel}`);

  if (Number.isFinite(bedValue)) {
    verdict(Math.abs(s.maxBedC - bedValue) <= 0.5,
      `bed command ${s.maxBedC.toFixed(0)} °C equals the preset's ${bedKey} ${bedC}`,
      `bed commanded ${s.maxBedC.toFixed(0)} °C but the preset's ${bedKey} is ${bedC}`);
  }

  // Every slot counts: a plate printed from slot 10 has 0 mm on slot 1 and is not empty.
  const used = perSlot.reduce((sum, v) => sum + (Number.isFinite(v) ? v : 0), 0);
  const usedMm = perSlot.length === 1 ? firstValue(h.get("filament used [mm]")) : used.toFixed(2);
  const layers = h.get("total layer number") ?? String(s.layers);
  const time = h.get("estimated printing time (normal mode)") ?? "?";
  if (perSlot.some((v) => Number.isFinite(v))) {
    verdict(used > 0, `filament used ${usedMm} mm, ${layers} layers, ${time}`, "filament used = 0 — empty slice");
  } else {
    note("filament used unreadable");
  }
  if (["0", "0.00"].includes(firstValue(h.get("total filament used [g]") ?? "1"))) {
    note("filament weight 0 g: the preset has no density; the length is right, the grams are not");
  }

  return {
    file: basename(path),
    generatedBy: h.get("generated by") ?? "?",
    lines,
    failures,
    warnings,
    facts: {
      layers, maxZ: s.maxZ, timeEstimate: time, filamentMm: usedMm, filamentType,
      nozzleC, bedC, bedType: bedType === "?" ? BED_TYPE : bedType,
      arcs: s.arcs, relativeMoves: s.relativeMoves, maxFeedXY: s.maxFeedXY, maxAccel: s.maxAccel,
      x: s.x, y: s.y,
    },
    code: failures.length ? 2 : 0,
  };
}
