/**
 * What a file is, before anything slices or sends it — and what the designer said about printing it, which is the
 * part no tool used to read. A project can say "base 15% infill, figure 0%" in prose and encode none of it.
 *
 *   SLICE    plain geometry — slice it fresh for the AD5M
 *   CONVERT  a project from another slicer — re-slice it with the AD5M presets
 *   CHECK    G-code — hold it to the printer before it goes anywhere
 *   REFUSE   sliced for another machine with no model inside; ask for the source file
 */
import { statSync } from "node:fs";
import { basename } from "node:path";

import { BED_XY, BED_Z, PRINTER_MODEL } from "./machine.js";
import { firstValue, header, scan } from "./gcode.js";
import { placedObjects, type PlacedObject } from "./geometry.js";
import { fitsBed, stlInfo, type StlInfo } from "./stl.js";
import {
  collapseFilaments, firstSlot, notes, objectSettings, type Notes, type ObjectSetting, projectSettings,
} from "./threemf.js";
import { Zip } from "./zip.js";

export type Verdict = "SLICE" | "CONVERT" | "CHECK" | "REFUSE";

export interface Inspection {
  file: string;
  path: string;
  megabytes: number;
  kind: "stl" | "project" | "gcode" | "unknown";
  verdict: Verdict;
  /** Why, when the verdict is not the obvious one. */
  because?: string;
  notes: Notes;
  mesh?: StlInfo;
  objects?: PlacedObject[];
  objectSettings?: ObjectSetting[];
  project?: {
    generator: string;
    printerModel: string;
    printerSettingsId: string;
    printSettingsId: string;
    layerHeight: string;
    nozzle: string;
    filaments: string[];
    filamentTypes: string[];
    supports: boolean;
    supportType: string;
    brim: string;
    infill: string;
    plates: number;
    extruders: string[];
    slicedPlates: string[];
  };
  gcode?: {
    generatedBy: string;
    printerModel: string;
    filament: string;
    filamentType: string;
    process: string;
    maxZ: number | null;
    layers: string;
    time: string;
    bambuHits: number;
  };
  fits?: boolean;
  /** Anything worth stopping for, in the order it was found. */
  warnings: string[];
}

export async function inspect(path: string): Promise<Inspection> {
  const file = basename(path);
  const low = file.toLowerCase();
  const megabytes = statSync(path).size / 1e6;
  const base = { file, path, megabytes, notes: {} as Notes, warnings: [] as string[] };

  if (low.endsWith(".stl")) {
    const mesh = stlInfo(path);
    const fits = fitsBed(mesh.size, BED_XY, BED_Z);
    const warnings: string[] = [];
    if (!fits) warnings.push(`exceeds ${BED_XY} × ${BED_XY} × ${BED_Z} mm — scaling or splitting is your call`);
    if (Math.max(...mesh.size) < 2) warnings.push("smaller than 2 mm on every axis — probably exported in inches or metres");
    return { ...base, kind: "stl", mesh, fits, verdict: "SLICE", warnings };
  }

  if (low.endsWith(".gcode")) {
    const h = header(path);
    const s = scan(path);
    const model = h.get("printer_model") ?? "?";
    const gcode = {
      generatedBy: h.get("generated by") ?? "?",
      printerModel: model,
      filament: h.get("filament_settings_id") ?? "?",
      filamentType: firstValue(h.get("filament_type")),
      process: h.get("print_settings_id") ?? "?",
      maxZ: s.maxZ,
      layers: h.get("total layer number") ?? String(s.layers),
      time: h.get("estimated printing time (normal mode)") ?? "?",
      bambuHits: s.bambuHits.length,
    };
    const foreign = model !== PRINTER_MODEL || s.bambuHits.length > 0;
    return {
      ...base, kind: "gcode", gcode, verdict: foreign ? "REFUSE" : "CHECK",
      ...(foreign ? { because: "sliced for another printer, and a .gcode has no model to re-slice — ask for the .3mf or .stl" } : {}),
      warnings: s.bambuHits.length ? [`${s.bambuHits.length} Bambu-only command(s), first at line ${s.bambuHits[0]?.line}`] : [],
    };
  }

  if (!low.endsWith(".3mf")) {
    return { ...base, kind: "unknown", verdict: "REFUSE", because: "not a file this reads: .stl, .3mf or .gcode", warnings: [] };
  }

  const zip = new Zip(path);
  try {
    const settings = projectSettings(zip);
    const objSettings = objectSettings(zip);
    const hasModel = zip.has("3D/3dmodel.model");
    const slicedPlates = zip.names().filter((n) => n.startsWith("Metadata/plate_") && n.endsWith(".gcode"));
    const warnings: string[] = [];

    // Orca forks keep Bambu's Application string, so the generator is read from an embedded gcode when there is one.
    let generator = "Orca/Bambu family";
    if (slicedPlates[0]) {
      for (const line of zip.readPrefixText(slicedPlates[0], 1 << 16).split("\n").slice(0, 5)) {
        if (line.startsWith("; generated by ")) {
          generator = line.slice("; generated by ".length).split(" on ")[0] ?? generator;
          break;
        }
      }
    }

    if (!hasModel) {
      return {
        ...base, kind: "project", verdict: "REFUSE", notes: {},
        because: "no 3D/3dmodel.model — a sliced-only export, with nothing to re-slice",
        warnings,
      };
    }

    const objects = await placedObjects(zip);
    const fits = objects.every((o) => fitsBed(o.size, BED_XY, BED_Z));
    if (!fits) warnings.push(`an object exceeds ${BED_XY} × ${BED_XY} × ${BED_Z} mm — scaling or splitting is your call`);

    const extruders = [...new Set(objSettings.map((o) => o.extruder).filter(Boolean))].sort();
    // What convert will change so the plate prints from the one extruder, said before it happens.
    const collapse = collapseFilaments(zip);
    for (const m of collapse.moved) warnings.push(`one extruder: ${m} — convert moves it`);
    for (const d of collapse.dropped) {
      warnings.push(`the designer's ${d} — convert takes it out; a pause there instead is your call`);
    }
    for (const k of collapse.kept) warnings.push(`the project's ${k} stays in the print`);

    const project = settings
      ? {
        generator,
        printerModel: firstSlot(settings["printer_model"]) || "?",
        printerSettingsId: firstSlot(settings["printer_settings_id"]) || "?",
        printSettingsId: firstSlot(settings["print_settings_id"]) || "?",
        layerHeight: firstSlot(settings["layer_height"]) || "?",
        nozzle: firstSlot(settings["nozzle_diameter"]) || "?",
        filaments: (Array.isArray(settings["filament_settings_id"]) ? settings["filament_settings_id"] : []) as string[],
        filamentTypes: (Array.isArray(settings["filament_type"]) ? settings["filament_type"] : []) as string[],
        supports: ["1", "true"].includes(firstSlot(settings["enable_support"])),
        supportType: firstSlot(settings["support_type"]) || "?",
        brim: firstSlot(settings["brim_type"]) || "?",
        infill: firstSlot(settings["sparse_infill_density"]) || "?",
        plates: Math.max(1, slicedPlates.length),
        extruders,
        slicedPlates: slicedPlates.map((p) => basename(p)),
      }
      : undefined;

    if (project && project.printerModel !== PRINTER_MODEL) {
      warnings.push("made for another printer — convert replaces machine, process and filament");
    }

    const alreadyOurs = project?.printerModel === PRINTER_MODEL && slicedPlates.length > 0;
    return {
      ...base,
      kind: "project",
      notes: notes(zip),
      objects,
      objectSettings: objSettings,
      ...(project ? { project } : {}),
      fits,
      verdict: alreadyOurs && fits ? "CHECK" : "CONVERT",
      ...(alreadyOurs && fits
        ? { because: "already sliced for the AD5M — its plate can be checked as it stands" }
        : {}),
      warnings,
    };
  } finally {
    zip.close();
  }
}
